apiVersion: v1
kind: Service
metadata:
  name: postgres-nosub
  labels:
    app: postgres-nosub
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: tasknosub-database
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-task
  labels:
    app: postgres-task
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: task-database