apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nosub-ssd
spec:
  storageClassName: nosub-faster   #Link claim with volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# How dow we want implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nosub-faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-ssd
spec:
  storageClassName: task-faster   #Link claim with volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
# How dow we want implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: task-faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
volumeBindingMode: WaitForFirstConsumer