apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkcmFjdXRlbjEiLCJwYXNzd29yZCI6IjMyYzUxNDJiLTI4NjItNDU0OS05NDg3LTY4NDEzZjI0MmExYyIsImVtYWlsIjoidHV5ZW5uZ3V5ZW5sZW1pbmhAZ21haWwuY29tIiwiYXV0aCI6IlpISmhZM1YwWlc0eE9qTXlZelV4TkRKaUxUSTROakl0TkRVME9TMDVORGczTFRZNE5ERXpaakkwTW1FeFl3PT0ifX19
kind: Secret
metadata:
  name: kubedocker
  namespace: default
type: kubernetes.io/dockerconfigjson